imread('img.jpg')
Griseviye=Rgb2gray(resim)
Histeq=histeq(griseviye)
Adjust=imadjust(Histeq,[0.05 0.2],[])
Bw=im2bw(adjust,0)
Kenar=edge(bw,’zerocross’)
Kenar=bwareaopen(kenar,31)
Final=imfill(kenar,’holes’)
se=strel('disk’,2)
final=imclose(final,se)
final=imopen(final,se)
se=strel('disk’,3)
final=imerode(final,se)
Final=bwareaopen(final,400)
